In [1]:
import sys

print(sys.executable)
print(sys.version)

d:\coding\SQL\.venv\Scripts\python.exe
3.14.5 (tags/v3.14.5:5607950, May 10 2026, 10:43:50) [MSC v.1944 64 bit (AMD64)]

In [2]:
import mysql.connector

print("MySQL Connector is installed successfully!")

MySQL Connector is installed successfully!

In [3]:
import mysql.connector

try:
    connection = mysql.connector.connect(
        host="localhost",
        port=3306,
        user="root",
        password="Darik@7978",
        database="orders"
    )

    if connection.is_connected():
        print("MySQL connected successfully!")

except mysql.connector.Error as error:
    print("Connection error:", error)

MySQL connected successfully!

In [4]:
cursor = connection.cursor()

cursor.execute("SELECT * FROM orders")

rows = cursor.fetchall()

for row in rows:
    print(row)

(101, 'Alice', 'Electronics', 5000)
(102, 'Aman', 'Clothing', 2000)
(103, 'Alice', 'Electronics', 7000)
(104, 'Bob', 'Clothing', 3000)
(105, 'Aman', 'Electronics', 4000)
(106, 'Alice', 'Clothing', 1000)

In [5]:
import pandas as pd

query = "SELECT * FROM orders"

df = pd.read_sql(query, connection)

df

C:\Users\danis\AppData\Local\Temp\ipykernel_16824\2313224424.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, connection)

   OrderID Customer     Category  Amount
0      101    Alice  Electronics    5000
1      102     Aman     Clothing    2000
2      103    Alice  Electronics    7000
3      104      Bob     Clothing    3000
4      105     Aman  Electronics    4000
5      106    Alice     Clothing    1000

In [6]:
df

   OrderID Customer     Category  Amount
0      101    Alice  Electronics    5000
1      102     Aman     Clothing    2000
2      103    Alice  Electronics    7000
3      104      Bob     Clothing    3000
4      105     Aman  Electronics    4000
5      106    Alice     Clothing    1000

In [7]:
df.describe()

          OrderID       Amount
count    6.000000     6.000000
mean   103.500000  3666.666667
std      1.870829  2160.246899
min    101.000000  1000.000000
25%    102.250000  2250.000000
50%    103.500000  3500.000000
75%    104.750000  4750.000000
max    106.000000  7000.000000

In [8]:
df["Amount"].sum()

np.int64(22000)